# Docker Compose file for Vapor
#
# Install Docker on your system to run and test
# your Vapor app in a production-like environment.
#
# Note: This file is intended for testing and does not
# implement best practices for a production deployment.
#
# Learn more: https://docs.docker.com/compose/reference/
#
#   Build images: docker-compose build
#      Start app: docker-compose up app
#       Stop all: docker-compose down
#
version: '3.7'

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  
services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/ -schemas=swift-flyway -user=postgres -password=password -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - postgres
  postgres:
    container_name: postgres-flyway
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    image: postgres:10.1-alpine
    ports:
      - "5432:5432"
  app:
    image: empty_vapor:latest
    depends_on:
      - postgres
    build:
      context: .
    environment:
      <<: *shared_environment
    ports:
      - '8080:8080'
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
